# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-22 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/users/')),
                ('tipo_role', models.CharField(choices=[('AD', 'Administrador'), ('EN', 'Entrenador'), ('DP', 'Deportista')], max_length=2)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'C\xe9dula de ciudadan\xeda')], max_length=2)),
                ('numero_documento', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(default='-', max_length=10)),
                ('direccion_residencia', models.CharField(max_length=80)),
                ('descripcion_persona', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Mi\xe9rcoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileUser')),
            ],
        ),
        migrations.AddField(
            model_name='modalidadpersona',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileUser'),
        ),
        migrations.AddField(
            model_name='modalidadpersona',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Modalidad'),
        ),
        migrations.AddField(
            model_name='modalidadpersona',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.NivelModalidad'),
        ),
    ]
