# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=45)),
                ('direccion_evento', models.CharField(max_length=80)),
                ('fecha_evento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
            ],
        ),
    ]
